import mongoose from 'mongoose';

const doctorSchema = new mongoose.Schema({
  name: { type: String, required: true },
  specialization: { type: String, required: true },
  experience: { type: String, default: '1 year' },
  rating: { type: Number, default: 0, min: 0, max: 5 },
  patients: { type: Number, default: 0 },
  available: { type: Boolean, default: true },
  phone: { type: String, default: '' },
  email: { type: String, required: true, unique: true },
  initials: { type: String, default: '' },
  department: { type: String, default: '' },
  consultation_fees: { type: Number, default: 500 },
  location: { type: String, default: '' },
  profile_photo: { type: String, default: '' },
  qualifications: { type: String, default: '' },
  bio: { type: String, default: '' },
  time_slots: { type: [String], default: ['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM'] },
  weekly_schedule: {
    type: Object,
    default: {
      monday: true, tuesday: true, wednesday: true,
      thursday: true, friday: true, saturday: false, sunday: false
    }
  },
  leaves: { type: [String], default: [] },
  leaveBalance: {
    sick: { type: Number, default: 12 },
    casual: { type: Number, default: 15 },
    earned: { type: Number, default: 20 },
    personal: { type: Number, default: 10 },
    maternity: { type: Number, default: 90 },
  },
  approved: { type: Boolean, default: false },
  user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  hospitalId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hospital', index: true },
  facilityId: { type: mongoose.Schema.Types.ObjectId, ref: 'Facility', index: true },
  facilityType: { type: String, enum: ['hospital', 'clinic', 'lab', 'pharmacy', ''], default: '' },
  reviews_count: { type: Number, default: 0 },
  signatureUrl: { type: String, default: '' },
  doctor_type: { type: String, enum: ['hospital', 'clinic'], default: 'hospital' },
  languages: { type: [String], default: [] },
  practice_type: { type: String, enum: ['private', 'corporate', ''], default: '' },
  areas_of_expertise: { type: [String], default: [] },
  services_offered: { type: [String], default: [] },
  surgeries_procedures: { type: [String], default: [] },
  education: { type: [Object], default: [] },
  work_experience: { type: [Object], default: [] },
  memberships: { type: [String], default: [] },
  awards: { type: [String], default: [] },
  registrations: { type: Object, default: {} },
  clinic_reception_phone: { type: String, default: '' },
  walk_in_accepted: { type: Boolean, default: false },
  in_house_pharmacy: { type: Boolean, default: false },
  in_house_lab: { type: Boolean, default: false },
  admission_available: { type: Boolean, default: false },
  emergency_consultation: { type: Boolean, default: false },
  surgery_available: { type: Boolean, default: false },
  home_visit: { type: Boolean, default: false },
  payment_modes: { type: [String], default: ['Cash', 'UPI', 'Card'] },
  opd_timings: { type: String, default: '9:00 AM – 5:00 PM' },
  workingHours: {
    start: { type: String, default: '09:00' },
    end: { type: String, default: '17:00' },
  },
  slotDuration: { type: Number, default: 15 },
  bufferPerHour: { type: Number, default: 1 },
  createdAt: { type: Date, default: Date.now },
});

export default mongoose.model('Doctor', doctorSchema);
