/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hello(): string
export declare function add(a: number, b: number): number
/** Run hello() `iterations` times and return the average nanoseconds per call. */
export declare function benchmarkHello(iterations: number): number
/** Run add() `iterations` times and return average nanoseconds per call. */
export declare function benchmarkAdd(iterations: number): number
/**
 * Validate that a file's magic bytes match its claimed MIME type.
 * Returns false for SVG (no reliable magic bytes) or content mismatch.
 */
export declare function validateMagicBytes(buffer: Uint8Array, mimetype: string): boolean
/**
 * Resize an image to exact dimensions and re-encode as JPEG.
 *
 * `quality` is 1-100 where higher is better (matches Sharp's quality scale).
 * Returns the JPEG-encoded buffer.
 */
export declare function resizeImage(input: Uint8Array, width: number, height: number, quality: number): Array<number>
/** Get image format and dimensions without decoding pixel data. */
export declare function getImageInfo(input: Uint8Array): string
/**
 * Generate a payment invoice PDF.
 *
 * Expects a JSON string with invoice data. Returns the PDF as a byte vector.
 */
export declare function generateInvoicePdf(dataJson: string): Array<number>
/**
 * Parse a CSV string into a JSON array of objects.
 * Each row becomes a JSON object with keys from the first row (header).
 * Returns a JSON string to avoid serde_json serialization overhead on the FFI boundary.
 */
export declare function parseCsv(input: string): string
/**
 * Serialize an array of objects to a CSV string.
 *
 * `rows_json` is a JSON string representing an array of objects.
 * `fields_json` is a JSON string representing an array of field names to use as columns.
 * Returns a CSV string with header row followed by data rows.
 */
export declare function toCsv(rowsJson: string, fieldsJson: string): string
/**
 * Generate a cryptographically secure random salt and hash an OTP.
 *
 * Returns a string in the format `salt_hex:hash_hex` where:
 * - `salt_hex` is a 16-byte random salt (hex-encoded, 32 chars)
 * - `hash_hex` is `SHA256(salt ++ otp)` (hex-encoded, 64 chars)
 *
 * This replaces bcrypt for OTP storage — OTPs are short-lived (10 min)
 * and single-use, so SHA-256 with a random salt provides adequate security
 * while being ~100x faster than bcrypt for verification.
 *
 * Mirrors `OTP.hashOTP()` in server/models/OTP.js.
 */
export declare function hashOtp(otp: string): string
/**
 * Verify an OTP against a stored hash using constant-time comparison.
 *
 * Supports two hash formats:
 * - New format: `salt_hex:hash_hex` (produced by `hash_otp`)
 * - Legacy bcrypt format: `$2a$...` or `$2b$...` (falls through to JS bcrypt)
 *
 * Returns `false` for legacy bcrypt hashes (caller should fall back to JS).
 * Mirrors `OTP.compareOTP()` in server/models/OTP.js.
 */
export declare function verifyOtpHash(otp: string, stored: string): boolean
/**
 * Generic constant-time comparison of two strings.
 *
 * Returns true if the strings are equal, using a constant-time algorithm
 * to prevent timing side-channel attacks.
 */
export declare function constantTimeCompare(a: string, b: string): boolean
